language: java
jdk:
    -openjdk8
    
dist: trusty

addons:
    sonarcloud:
        organization: vlromano
        token:
            secure: b985a8c217b9ff586608fc37fb15f993a393b2b6
        
script: 
- ant build
- sonar-scanner
