language: java
jdk:
    -openjdk8

addons:
    sonarcloud:
        organization: vlromano
        token: b985a8c217b9ff586608fc37fb15f993a393b2b6
            
        
script: 
- ant build
- sonar-scanner
